/*
===================================================================
                           Mapping
===================================================================

Since the API and Adventure Works systems do not share business keys, a simulated 
customer mapping layer is created to represent identity resolution. This includes 
a confidence score to reflect uncertainty in the match and a match type to indicate 
how the match was derived. 

For demonstration purposes, matches are generated by bucketing customer IDs using 
the modulo operator, and match confidence values are randomized. This allows us 
to showcase the process of creating a mapping table, inserting data, and working 
with integration logic in a data warehouse context.

*/


-- Create DW.CustomerMapping
CREATE TABLE DW.CustomerMapping (
    mapping_id INT IDENTITY PRIMARY KEY,
    api_customer_id INT,
    aw_customer_id INT,
    match_confidence DECIMAL(3,2),  -- realism
    match_type VARCHAR(50)          -- how it was matched
);


-- Populate DW.CustomerMapping
INSERT INTO DW.CustomerMapping (
    api_customer_id,
    aw_customer_id,
    match_confidence,
    match_type
)
SELECT TOP 300
    dc.customer_id,
    aw.customer_id_aw,
    ROUND(RAND(CHECKSUM(NEWID())), 2),
    'simulated_match'
FROM DW.DimCustomer dc
JOIN DW.AWDimCustomer aw
    ON ABS(dc.customer_id % 1000) = ABS(aw.customer_id_aw % 1000);


-- Create View
CREATE VIEW Analytics.VwUnifiedCustomers AS
SELECT
    dc.customer_key,
    dc.customer_id AS api_customer_id,
    m.aw_customer_id,
    m.match_confidence
FROM DW.DimCustomer dc
LEFT JOIN DW.CustomerMapping m
    ON dc.customer_id = m.api_customer_id;