/*
===================================================================
                           Mapping
===================================================================

Since the API and Adventure Works systems do not share business keys, a simulated 
customer mapping layer is created to represent identity resolution. This includes 
a confidence score to reflect uncertainty in the match and a match type to indicate 
how the match was derived. 

For demonstration purposes, matches are generated by bucketing customer IDs using 
the modulo operator, and match confidence values are randomized. This allows us 
to showcase the process of creating a mapping table, inserting data, and working 
with integration logic in a data warehouse context.

*/


-- Create DW.CustomerMapping
CREATE TABLE DW.CustomerMapping (
    mapping_id INT IDENTITY PRIMARY KEY,
    api_customer_key INT,
    aw_customer_key INT,
    match_confidence DECIMAL(3,2),  -- realism
    match_type VARCHAR(50)          -- how it was matched
);


-- Populate DW.CustomerMapping
WITH AWCommonCustomers AS (
    SELECT TOP (1000)
        customer_key_aw,
        customer_id_aw,
        ABS(customer_id_aw % 10000) AS common_customer_id_aw
    FROM DW.AWDimCustomer
)
INSERT INTO DW.CustomerMapping (
    api_customer_key,
    aw_customer_key,
    match_confidence,
    match_type
)
SELECT
    dc.customer_key,
    aw.customer_key_aw,
    ROUND(RAND(CHECKSUM(NEWID())), 2),
    'simulated_match'
FROM DW.DimCustomer AS dc
JOIN AWCommonCustomers AS aw
    ON dc.customer_id = aw.common_customer_id_aw
WHERE dc.is_current = 1;


-- Create View
CREATE VIEW Analytics.VwUnifiedCustomers AS
SELECT
    dc.customer_key AS api_customer_key,
    m.aw_customer_key,
    m.match_confidence
FROM DW.DimCustomer dc
LEFT JOIN DW.CustomerMapping m
    ON dc.customer_key = m.api_customer_key;