"""
-----------------------------------
      Generate Campaigns CSV
-----------------------------------

The campaigns CSV should have much fewer than your transactional data,
but enough to create meaningful relationships.

If you create hundreds of thousands of campaigns, that would be unrealistic.

In real ecommerce:

    - Campaigns are low-frequency, high-impact entities
    - Events/orders are high-frequency outcomes

---

Unlike other simulators in this project, this one isn't directly related to
the pipeline (the "main_campaign_pipeline.py" in this case): In this case,
the extractor script will get the data generated by this script, and that
extractor will be the one directly related to the campaign pipeline.

"""



import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os

# -----------------------------
# RANDOM GENERATOR
# -----------------------------
rng = np.random.default_rng(42)

# -----------------------------
# CONFIG
# -----------------------------
N_CAMPAIGNS = 200

CHANNELS = [
    "Email",
    "Google Ads",
    "Facebook Ads",
    "Organic Search",
    "Organic Social",
    "Influencer",
    "Affiliate",
    "Display Ads"
]

START_BASE = datetime(2025, 1, 1)
END_BASE = datetime(2025, 12, 31)

OUTPUT_PATH = os.path.join(
    os.path.dirname(__file__),
    "../../data/raw/campaigns.csv"
)

# -----------------------------
# LOGIC FUNCTIONS
# -----------------------------

def generate_budget(channel):
    if channel == "Email":
        return round(rng.random.uniform(500, 5000), 2)
    elif channel == "Google Ads":
        return round(rng.random.uniform(8000, 40000), 2)
    elif channel == "Facebook Ads":
        return round(rng.random.uniform(5000, 30000), 2)
    elif channel == "Display Ads":
        return round(rng.random.uniform(10000, 50000), 2)
    elif channel == "Influencer":
        return round(rng.random.uniform(2000, 20000), 2)
    elif channel == "Affiliate":
        return round(rng.random.uniform(3000, 25000), 2)
    elif channel == "Organic Search":
        return round(rng.random.uniform(1000, 8000), 2)
    else:  # Organic Social
        return round(rng.random.uniform(500, 6000), 2)


def generate_duration(channel):
    if channel == "Email":
        return rng.random.randint(1, 7)
    elif channel in ["Google Ads", "Facebook Ads"]:
        return rng.random.randint(14, 45)
    elif channel == "Display Ads":
        return rng.random.randint(30, 90)
    elif channel == "Affiliate":
        return rng.random.randint(20, 60)
    else:  # Organic channels + Influencer
        return rng.random.randint(7, 30)


# -----------------------------
# MAIN GENERATION
# -----------------------------

def generate_campaigns(n_campaigns=N_CAMPAIGNS):
    data = []

    for i in range(1, n_campaigns + 1):
        channel = rng.random.choice(CHANNELS)

        # Random start → ensures overlap naturally
        start_date = START_BASE + timedelta(days=rng.random.randint(0, 300))

        duration = generate_duration(channel)
        end_date = start_date + timedelta(days=duration)

        if end_date > END_BASE:
            end_date = END_BASE

        budget = generate_budget(channel)

        data.append([
            i,
            channel,
            start_date.strftime("%Y-%m-%d"),
            end_date.strftime("%Y-%m-%d"),
            budget
        ])

    df = pd.DataFrame(data, columns=[
        "campaign_id",
        "channel",
        "start_date",
        "end_date",
        "budget"
    ])

    return df


def save_campaigns(df):
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False)
    print(f"Campaigns file saved to: {OUTPUT_PATH}")
    print(f"Total campaigns generated: {len(df)}")


# -----------------------------
# ENTRY POINT
# -----------------------------

if __name__ == "__main__":
    df_campaigns = generate_campaigns()
    save_campaigns(df_campaigns)